### ISSUE TITLE
Unexpected token .

### ISSUE THREAD

**Issue by eladdekel** [PrismarineJS/prismarine-nbt#50]
`root:~/new2/node_modules/prismarine-nbt# cd test
root:~/new2/node_modules/prismarine-nbt/test# ls
datatypes.js  nbt-cross-encode.js  nbt-spec.js
root@:~/new2/node_modules/prismarine-nbt/test# node nbt-spec.js
/root/new2/node_modules/prismarine-nbt/nbt.js:165
    const type = value[0]?.type ?? 'end'
                          ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/new2/node_modules/prismarine-nbt/test/nbt-spec.js:6:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)`

**Comment by u9g** [comment]
update node
