### ISSUE TITLE
Not working with minecraft version 1.18.1

### ISSUE THREAD

**Issue by DevanshRathi1** [PrismarineJS/prismarine-nbt#60]
Package version: 2.1.0
Node version: 16.13.0

I am trying to read a `.mca` file that was made by minecraft version 1.18.1. 

This is the code that produced the issue (it is the same as the example in the README):

```
import fs from "fs/promises";
import nbt from "prismarine-nbt";

async function test() {
    const buffer = await fs.readFile(`${directory}/r.0.0.mca`);
    const { parsed, type } = await nbt.parse(buffer);
    console.log("JSON serialized", JSON.stringify(result, null, 2));
    fs.createWriteStream("file.nbt").write(nbt.writeUncompressed(result, type)); // Write it back
}

test();
```

Error:
```
undefined:32
        if (c === '\0') throw new Error('unexpected tag end')
                              ^

Error: Read error for undefined : unexpected tag end
    at Object.readPString [as nbtTagName] (eval at compile (/Users/<directory>node_modules/protodef/src/compiler.js:258:12), <anonymous>:32:31)
    at nbt (eval at compile (/Users/<directory>node_modules/protodef/src/compiler.js:258:12), <anonymous>:150:61)
    at CompiledProtodef.read (/Users/<directory>node_modules/protodef/src/compiler.js:70:12)
    at e.message (/Users/<directory>node_modules/protodef/src/compiler.js:111:49)
    at tryCatch (/Users/<directory>node_modules/protodef/src/utils.js:50:16)
    at CompiledProtodef.parsePacketBuffer (/Users/<directory>node_modules/protodef/src/compiler.js:111:29)
    at parseAs (/Users/<directory>node_modules/prismarine-nbt/nbt.js:63:31)
    at Object.parse (/Users/<directory>node_modules/prismarine-nbt/nbt.js:121:17)
    at test (file:///Users/<directory>server/trial/nbt.js:11:40)
```

**Comment by rom1504** [comment]
Can you check the prismarine provider anvil PR on the topic ?

**Comment by electrovir** [comment]
I'm getting the same error on region data in 1.19

**Comment by meza** [comment]
Same with 1.20.2

**Comment by rom1504** [comment]
Completely different topic for 1.20.2, please open another issue
