### ISSUE TITLE
Can I write it back to the same compressed type it originally was?

### ISSUE THREAD

**Issue by skeddles** [PrismarineJS/prismarine-nbt#86]
I'm trying to read map files. I am able to decompress and read them just fine. But I can't figure out how to write them back to the same format. 

Here is my attempt to write the same data back to the file. 

```
const nodeGzip = require('node-gzip');
const fs = require('fs');
const nbt = require('prismarine-nbt');

const inputFileName = 'maps/map_4.dat';
const outputFileName = 'map_repack_test.dat';

//read the map data file into memory
fs.readFile(inputFileName, function(error, gzippedMapData) {
    if (error) throw error;

	console.log('read file', gzippedMapData.length);
	// un gzip the map data file to return the nbt data
	nodeGzip.ungzip(gzippedMapData).then((nbtMapData) => {

		//parse the nbt data into a json object
		nbt.parse(nbtMapData, function(error, jsonMapData) {
			console.log('raw data:',jsonMapData);
			console.log('data compression type: ', jsonMapData.type);
			
			//now repack the map data back into a file
			fs.createWriteStream(outputFileName).write(nbt.writeUncompressed(jsonMapData.value.data.value, jsonMapData.type))
		});
	});
});

```

The output and error look like this:

```
read file 2672
raw data: {
  type: 'compound',
  name: '',
  value: {
    DataVersion: { type: 'int', value: 3578 },
    data: { type: 'compound', value: [Object] }
  }
}
data compression type:  compound
Y:\Projects\Modding\Minecraft\mapmod\node\node_modules\prismarine-nbt\nbt.js:55
  return protos[proto].createPacketBuffer('nbt', value)
                       ^

TypeError: Cannot read properties of undefined (reading 'createPacketBuffer')
    at Object.writeUncompressed (Y:\Projects\Modding\Minecraft\mapmod\node\node_modules\prismarine-nbt\nbt.js:55:24)
    at Y:\Projects\Modding\Minecraft\mapmod\node\testrepacking.js:26:51
    at Object.parse (Y:\Projects\Modding\Minecraft\mapmod\node\node_modules\prismarine-nbt\nbt.js:157:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by skeddles** [comment]
nevermind, i was just doing something wrong
